name: Generate Pac-Man Game

on:
  schedule:
    - cron: "0 */24 * * *" # Updates automatically every 24 hours
  workflow_dispatch:      # Allows manual trigger button in UI
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Step 1: Ensure workspace exists by checking out the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Generate the SVGs into the workspace
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Step 3: Push the generated files to the output branch
      - name: Push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
